server:
  port: 8083

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/microservices03

    username: root
    password: 278756
    driver-class-name: com.mysql.cj.jdbc.Driver
    
  application:
    name: Rating-service

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

        

eureka:
  instance:
    ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      deafaultZone: http://localhost:8761/eureka